<?php $_helper = Mage::helper('vtiseocore') ?>
<div class="content-header">
    <h3><?php echo $this->__('SEO Checklist') ?></h3>
</div>
<p><?php echo $this->__('This page contains a simple checklist for our recommended configuration of Magento to maximise SEO performance. This extension checks default scope configuration values only, values specific to a website or store view cannot be checked.') ?></p>
<div class="content-header">
    <br/>
    <h4><?php echo $this->__('SEO Settings') ?></h4>

    <p><?php echo $this->__('This section checks the additional settings made available by SEO Extension that can be configured for better SEO performance.') ?></p>
</div>

<div class="entry-edit">
    <ul class="messages">

        <?php if (!Mage::getStoreConfig('vtiseocore/defaultseo/noindexparams')): ?>
            <li class="error-msg">
                <span><?php echo $this->__('The NOINDEX Meta Tag for parameter based category pages is currently disabled.') ?>
                    <a href="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/system_config/edit/section/vtiseocore') ?>"><?php echo $this->__('Go fix it') ?></a></span>
            </li>
        <?php else: ?>
            <li class="success-msg">
                <span><?php echo $this->__('Parameter-based category pages have "noindex" set in robots') ?></span></li>
        <?php endif; ?>

        <?php if (!Mage::getStoreConfig('vtiseocore/defaultseo/enablecmscanonical')): ?>
            <li class="error-msg">
                <span><?php echo $this->__('You have not enabled canonical link tags on CMS pages. Please enable
                this so that all CMS pages have a canonical URL set.') ?>
                    <a href="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/system_config/edit/section/vtiseocore') ?>"><?php echo $this->__('Go fix it') ?></a></span>
            </li>
        <?php else: ?>
            <li class="success-msg">
                <span><?php echo $this->__('You have enabled canonical link meta tags for CMS pages.') ?></span>
            </li>
        <?php endif; ?>

        <?php if (Mage::getStoreConfig('vtiseocore/defaultseo/noindexparamssearch')) : ?>
            <li class="success-msg">
                <span><?php echo $this->__('NOINDEX has been added to search result pages.') ?></span></li>
        <?php else: ?>
            <li class="error-msg">
                <span><?php echo $this->__('Search result pages are currently indexable, set them to NOINDEX.') ?> <a
                            href="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/system_config/edit/section/vtiseocore') ?>"><?php echo $this->__('Go fix it') ?></a></span>
            </li>
        <?php endif ?>

        <?php if (Mage::getStoreConfig('vtiseocore/defaultseo/noindexparamsparameterpages')) : ?>
            <li class="success-msg">
                <span><?php echo $this->__('NOINDEX has been added to param pages.') ?></span></li>
        <?php else: ?>
            <li class="error-msg">
                <span><?php echo $this->__('Param pages are currently indexable, set them to NOINDEX.') ?> <a
                            href="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/system_config/edit/section/vtiseocore') ?>"><?php echo $this->__('Go fix it') ?></a></span>
            </li>
        <?php endif ?>

    </ul>
</div>

<div class="content-header">
    <br/>
    <h4><?php echo $this->__('Magento Configuration Settings') ?></h4>

    <p><?php echo $this->__('This section checks Magento settings that can be configured for better SEO performance.') ?></p>
</div>

<div class="entry-edit">
    <ul class="messages">
        <?php if (!Mage::getStoreConfig('web/seo/use_rewrites')): ?>
            <li class="error-msg">
                <span><?php echo $this->__('"Use Web Server Rewrites" is currently set to no. Please set to yes within the "Search Engine Optimizations" settings.') ?>
                    <a href="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/system_config/edit/section/web') ?>"><?php echo $this->__('Go fix it') ?></a></span>
            </li>
        <?php else: ?>
            <li class="success-msg"><span><?php echo $this->__('Web Server Rewrites are enabled correctly') ?></span>
            </li>
        <?php endif; ?>
        <?php if (!Mage::getStoreConfig('catalog/seo/category_canonical_tag')): ?>
            <li class="error-msg">
                <span><?php echo $this->__('Category Canonical Meta Tags are not enabled. Please set Search Engine Optimizations > Use Canonical Link Meta Tag for Categories to Yes.') ?>
                    <a href="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/system_config/edit/section/catalog') ?>"><?php echo $this->__('Go fix it') ?></a></span>
            </li>
        <?php else: ?>
            <li class="success-msg">
                <span><?php echo $this->__('Category Canonical Tags have been setup correctly') ?></span></li>
        <?php endif; ?>
        <?php if (!Mage::getStoreConfig('catalog/seo/product_canonical_tag')): ?>
            <li class="error-msg">
                <span><?php echo $this->__('Product Canonical Meta Tags are not enabled. Please set Search Engine Optimizations > Use Canonical Link Meta Tag for Products to Yes.') ?>
                    <a href="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/system_config/edit/section/catalog') ?>"><?php echo $this->__('Go fix it') ?></a></span>
            </li>
        <?php else: ?>
            <li class="success-msg">
                <span><?php echo $this->__('Product Canonical Tags have been configured correctly') ?></span></li>
        <?php endif; ?>

<!--        --><?php //if (Mage::getStoreConfig('catalog/seo/product_use_categories')): ?>
<!--            <li class="error-msg">-->
<!--                <span>--><?php //echo $this->__('Categories are currently used in your Product URL path. Please set Search Engine Optimizations > Use Categories Path for Product URLs to No to ensure products can only be accessed via the canonical URL.') ?>
<!--                    <a href="--><?php //echo Mage::helper("adminhtml")->getUrl('adminhtml/system_config/edit/section/catalog') ?><!--">--><?php //echo $this->__('Go fix it') ?><!--</a></span>-->
<!--            </li>-->
<!--        --><?php //else: ?>
<!--            <li class="success-msg">-->
<!--                <span>--><?php //echo $this->__('Product URL\'s only exist under the canonical tag') ?><!--</span></li>-->
<!--        --><?php //endif; ?>

    </ul>
</div>

<div class="content-header">
    <br/>
    <h4><?php echo $this->__('Default Values') ?></h4>

    <p><?php echo $this->__('This section checks for any default Magento values/text that have not been updated since installing.') ?></p>

</div>

<div class="entry-edit">
    <ul class="messages">

        <?php if (Mage::getStoreConfig('design/head/default_robots') != "INDEX,FOLLOW"): ?>
            <li class="error-msg">
                <span><?php echo $this->__('Search Engine are currently blocked from caching and/or crawling your website. Unless you\’re in the development stage, please "Default Robots" to INDEX, FOLLOW within the HTML Head settings.') ?>
                    <a href="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/system_config/edit/section/design') ?>"><?php echo $this->__('Go fix it') ?></a></span>
            </li>
        <?php else: ?>
            <li class="success-msg">
                <span><?php echo $this->__('The site’s Meta Robots Tag allows search engines to both crawl and cache your website.') ?></span>
            </li>
        <?php endif; ?>
        <?php if (!Mage::helper('vtiseocore')->checkDefaultStoreNames()): ?>
            <li class="error-msg">
                <span><?php echo $this->__('You should change your store name from "Default Store View"') ?> <a
                            href="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/system_store') ?>"><?php echo $this->__('Go fix it') ?></a></span>
            </li>
        <?php else: ?>
            <li class="success-msg"><span><?php echo $this->__('Your store view name has been customized.') ?></span>
            </li>
        <?php endif; ?>

        <?php if (Mage::getStoreConfig('design/header/logo_alt') == "Magento Commerce"): ?>
            <li class="error-msg">
                <span><?php echo $this->__('Your logo alt text has not been changed from the default "Magento Commerce".') ?>
                    <a href="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/system_config/edit/section/design') ?>"><?php echo $this->__('Go fix it') ?></a></span>
            </li>
        <?php else: ?>
            <li class="success-msg"><span><?php echo $this->__('Your logo alt text name has been customized.') ?></span>
            </li>
        <?php endif; ?>

        <?php $noRoutePage = Mage::getStoreConfig('web/default/cms_no_route'); ?>
        <?php $cmsPage = Mage::getModel('cms/page')->load($noRoutePage, 'identifier'); ?>
        <?php if ($cmsPage->getId()) : ?>
            <?php if (
                strpos($cmsPage->getContent(), "Whoops, our bad...") ||
                strpos($cmsPage->getContent(), "The page you requested was not found, and we have a fine guess why.") ||
                strpos($cmsPage->getContent(), "If you typed the URL directly, please make sure the spelling is correct.") ||
                strpos($cmsPage->getContent(), "If you clicked on a link to get here, the link is outdated.") ||
                strpos($cmsPage->getContent(), "Have no fear, help is near! There are many ways you can get back on track with") ||
                strpos($cmsPage->getContent(), "Use the search bar at the top of the page to search for your products.") ||
                strpos($cmsPage->getContent(), "Follow these links to get you back on track")

            ) : ?>
                <li class="error-msg">
                    <span><?php echo $this->__('Your 404 error page contains some of the default Magento text, you should update it with new content.') ?>
                        <a href="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/cms_page/edit/page_id/' . $cmsPage->getId()) ?>"><?php echo $this->__('Go change it') ?></a></span>
                </li>
            <?php else: ?>
                <li class="success-msg">
                    <span><?php echo $this->__('Your 404 page has been customised sufficiently, well done!') ?></span>
                </li>
            <?php endif ?>
        <?php endif ?>

    </ul>
</div>
