<fieldset ng-class="vti-info">
    <table>
        <tr>
            <td width="10"></td>
            <td>
                <h3>VTISEO version <?php echo $this->getModuleVersion() ?></h3>
                <p><strong><a href="<?php echo $this->getGitHubPage() ?>" target="_blank">Support</a></strong> - create
                    a GitHub issue
                    <br/><strong><a href="<?php echo $this->getVTIBlogPost() ?>" target="_blank">How To</a></strong>
                    - read our official blog post for our how-to video
                    <br/><strong><a target="_blank" href="<?php echo $this->getGitHubPage() ?>">Collaborate</a></strong>
                    - visit our GitHub repository and send a pull request</p>
            </td>
        </tr>
    </table>
</fieldset>